"""
Django settings for AlumniSys project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import urllib
import django_heroku
from pymongo.mongo_client import MongoClient


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMP_DIR = os.path.join(BASE_DIR,'template')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p7gqo*7o6koe-lh@h3&75nxkr@y*v611w$y)epb$u^pgs^mwor'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
	'alumnisys.herokuapp.com',
	'localhost'
]

# Change Defualt Model to Custom
AUTH_USER_MODEL = 'Accounts.Account'
AUTHENTICATION_BACKENDS = [
	# Social Backends...

	# Defult Backend
	'django.contrib.auth.backends.ModelBackend',
]


# Application definition
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'phonenumber_field',
	'ckeditor',

	'Accounts',
	'Friends',
	'Posts',
	'Jobs',
]

CKEDITOR_CONFIGS = {
	'default': {
		# 'toolbar': None,
		'width': 'auto',
	},
}

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AlumniSys.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'AlumniSys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
	'default': {
		'ENGINE': 'djongo',
		'NAME': 'AAAiSysDB',
		'ENFORCE_SCHEMA': False,
	}
}

MongoClient.HOST = 'mongodb+srv://jatin:Jatinbho%21r121@aaaisys-t.ijmmd.mongodb.net/AlumniSysDB?retryWrites=true&w=majority'

#'HOST' : 'mongodb://<dbuser>:<dbpassword>@ds259144.mlab.com:59144/<db-name>',
# #that is your connection link with your username, password and db name..
# 'USER' : '<dbuser>',
# 'PASSWORD' : '<dbpassword>',

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	# {
	#     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	# },
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'static'),
]

# Media files (Files User Upload like Profile Pic., etc)
MEDIA_URL = '/media/'
MEDIAFILES_DIR = [
	os.path.join(BASE_DIR, 'media'),
]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Avatar File Size
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB = 10 * 1024 *1024
TEMP = os.path.join(BASE_DIR, 'media/profile_pics/temp')

# Authentication (Login/Logout)
LOGIN_REDIRECT_URL = 'Posts:all-posts' #Change it as Post Created..
LOGOUT_REDIRECT_URL = 'index'

# SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jatinbhoir6@gmail.com'
EMAIL_HOST_PASSWORD = 'xvitfzpaoksprolr'


# Heroku
django_heroku.settings(locals())
